/**
 * Seed data for the NexterLaw AI Readiness Snapshot knowledge base.
 * All entries authored in the style specified by Dr. Siamak Goudarzi / NexterLaw.
 * Source references are to publicly available SRA, ICO, and Law Society guidance.
 */

import type { FirmSizeBand } from '@/types';

export interface KBEntry {
  category: 'REGULATORY_GUIDANCE' | 'USE_CASE_LIBRARY' | 'RISK_LIBRARY' | 'CONDITIONAL_EU_LAYER' | 'TOOL_CATEGORIES';
  title: string;
  bodyText: string;
  appliedToPracticeTypes: string[];   // [] = all
  appliedToFirmSizes: FirmSizeBand[]; // [] = all
  sourceReference?: string;
  weight: number;
  isEuLayerEntry?: boolean;
}

const ALL_PRACTICES: string[] = [];
const ALL_SIZES: FirmSizeBand[] = [];

export const KNOWLEDGE_BASE_ENTRIES: KBEntry[] = [

  // ─── REGULATORY GUIDANCE (~20 entries) ───────────────────────────────────

  {
    category: 'REGULATORY_GUIDANCE',
    title: 'SRA Position on AI Use by Solicitors',
    bodyText: 'The SRA has confirmed that its existing professional conduct obligations — competence, supervision, confidentiality and honesty — apply fully to the use of AI tools. Solicitors remain personally responsible for work product generated with AI assistance. Where AI is used in delivering legal services, the supervising solicitor must understand the output well enough to stand behind it as their own professional work.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'SRA, AI and Technology guidance, 2024',
    weight: 2.0,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'SRA Competence Duty and AI Outputs',
    bodyText: 'The SRA competence framework requires solicitors to apply a sufficient level of knowledge and skill to each matter. Relying on AI output without verifying accuracy or understanding its reasoning may breach the competence duty under the SRA Standards and Regulations. Firms should have documented processes for checking AI-generated content before it is relied upon or shared with clients.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'SRA Standards and Regulations, para 3.2 (Competence)',
    weight: 1.8,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'SRA Confidentiality and AI Tools',
    bodyText: 'SRA Rule 6 requires solicitors to keep client confidential information private. Inputting client details, case facts, or matter-specific data into third-party AI tools — including general-purpose large language models — may breach confidentiality unless you have verified the tool\'s data handling terms. Many widely used AI tools train on user inputs by default; firms should check and switch off training modes or use enterprise-tier products with appropriate data processing agreements in place.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'SRA Code of Conduct, Rule 6.3',
    weight: 2.0,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'UK GDPR Obligations When Using AI with Client Data',
    bodyText: 'Passing personal data about clients or counterparties to an AI tool constitutes processing under UK GDPR. Firms must have a lawful basis for that processing, a Data Processing Agreement (DPA) with the AI provider, and must ensure data is not transferred outside the UK/EEA without adequate safeguards. For high-risk processing (such as AI analysing data about vulnerable individuals), a Data Protection Impact Assessment (DPIA) is required before the processing begins.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'UK GDPR Articles 6, 28, 44; ICO Guidance on AI and Data Protection, 2023',
    weight: 2.0,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'ICO DPIA Trigger: AI Processing Sensitive Legal Data',
    bodyText: 'The ICO has confirmed that using AI to process sensitive personal data — including data relating to health, criminal offences, financial vulnerability, or family breakdown — is likely to require a DPIA under Article 35 UK GDPR. Law firms in family, criminal, personal injury, and immigration practice should assess each AI use case to determine whether a DPIA is needed before deployment.',
    appliedToPracticeTypes: ['family', 'criminal', 'personal-injury', 'immigration', 'private-client-wills-probate'],
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'ICO Guidance on DPIAs, 2023; UK GDPR Article 35',
    weight: 1.8,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'Law Society Practice Note: Technology and AI in Legal Practice',
    bodyText: 'The Law Society has published guidance emphasising that solicitors owe a duty of technology competence — being aware of and able to manage the technological implications of legal practice. This includes understanding the capabilities and limitations of AI tools used in their practice, ensuring appropriate supervision, and advising clients where relevant about AI use in their matter.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'Law Society Practice Note: Technology and Legal Practice, 2023',
    weight: 1.5,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'Professional Indemnity Insurance: AI-Related Questions at Renewal',
    bodyText: 'A growing number of PII insurers are including AI-use questions in renewal questionnaires. Firms that cannot demonstrate governance of their AI tools — including knowing which tools staff use, whether data is kept confidential, and whether outputs are verified — may face higher premiums or coverage restrictions. Maintaining a written AI position statement is increasingly an underwriting expectation.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'SRA Minimum Terms and Conditions for PII; broker market intelligence 2024',
    weight: 1.6,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'PII Exposure: AI-Assisted Drafting Errors',
    bodyText: 'Solicitors have faced disciplinary proceedings and complaints where AI-assisted drafts contained hallucinated case citations, incorrect legal positions, or confidential data leakage. PII policies cover negligence, but firms must demonstrate a reasonable review process was in place. Failing to catch an AI error that a competent review would have identified may affect indemnity.',
    appliedToPracticeTypes: ['litigation-dispute-resolution', 'corporate-ma', 'commercial-ip-it', 'conveyancing-property'],
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'SRA Case Studies on AI complaints; PII market guidance 2024',
    weight: 1.7,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'Client Transparency: AI Disclosure Best Practice',
    bodyText: 'While no UK rule currently mandates disclosure of AI use in all circumstances, the SRA expects solicitors to be honest with clients about how their work is done. Best practice — increasingly expected by sophisticated corporate clients — is to have a clear client-facing AI use statement, and to disclose material AI use in client care letters or engagement terms. Failure to disclose AI use where a client would reasonably expect to know may breach Principle 4 (honesty) or Rule 8.6 (information about costs).',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'SRA Principle 4; SRA Code of Conduct Rule 8.6; Law Society AI Guidance 2023',
    weight: 1.5,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'Client Procurement: AI Questionnaires from Corporate Clients',
    bodyText: 'Large corporate and financial services clients increasingly send AI due diligence questionnaires to their panel law firms. These questionnaires ask about AI tools in use, data handling, vendor vetting, staff training, and governance policies. Firms that cannot respond substantively risk removal from panels. This pressure is strongest in M&A, banking, and commercial litigation mandates.',
    appliedToPracticeTypes: ['corporate-ma', 'litigation-dispute-resolution', 'commercial-ip-it', 'full-service'],
    appliedToFirmSizes: ['MEDIUM', 'LARGE', 'ENTERPRISE'],
    sourceReference: 'In-house counsel survey data; panel firm questionnaire benchmarking, 2024',
    weight: 1.7,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'SRA Accountability: Named Responsibility for AI',
    bodyText: 'The SRA\'s broader accountability frameworks — including COFA obligations and partner responsibility under the Code for Firms — require firms to have clear management of risk. The absence of a named individual responsible for AI governance is itself a governance gap. Regulators expect firms to be able to demonstrate clear accountability for technology risk, consistent with their responsibilities under the Code for Firms para 2.1.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    sourceReference: 'SRA Code of Conduct for Firms, para 2.1; SRA Technology Guidance 2024',
    weight: 1.6,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'Data Residency: Where AI Processes Your Client Data',
    bodyText: 'Many AI tools process data in the United States or other non-UK jurisdictions. Under UK GDPR, transfers of personal data outside the UK require either an adequacy decision, Standard Contractual Clauses (SCCs), or another valid transfer mechanism. Firms must check their AI vendor\'s data processing agreement to confirm where data is stored, processed, and retained — and ensure they have appropriate transfer safeguards.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'UK GDPR Chapter V; ICO International Transfer Guidance 2023',
    weight: 1.6,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'SRA Supervision Requirements for AI Use',
    bodyText: 'Under SRA Principle 7 and Code para 4.2, solicitors must ensure proper supervision of work carried out within their firm. This obligation extends to work assisted by AI. A supervising partner or senior solicitor must be able to review, understand, and vouch for AI-assisted output — a requirement that has direct implications for firms where junior staff use AI tools without structured oversight.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'SRA Code of Conduct for Solicitors, para 4.2; SRA Principle 7',
    weight: 1.7,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'ICO Guidance: Automated Decision-Making and AI',
    bodyText: 'If an AI tool makes or significantly influences a decision affecting a client — for example, an automated risk assessment or eligibility decision — this may engage Article 22 UK GDPR rights against solely automated decisions. Firms should identify any AI use that could constitute automated decision-making and ensure human review is built into the workflow.',
    appliedToPracticeTypes: ['immigration', 'employment', 'personal-injury', 'family'],
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'UK GDPR Article 22; ICO Guidance on Automated Decision-Making 2023',
    weight: 1.4,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'Record-Keeping Obligations for AI-Assisted Work',
    bodyText: 'Firms have file-keeping obligations under the SRA Accounts Rules and general professional practice standards. Where AI has been used in preparing advice, drafting documents, or conducting research, there should be a record of this on the matter file — both for supervision purposes and to allow the work to be reconstructed in any complaint, dispute, or audit situation. The absence of such records is a traceability gap under the CLEAR TRUST framework.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'SRA Accounts Rules; SRA Standards and Regulations, principle of accountability',
    weight: 1.5,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'Staff AI Training: SRA Competence Implications',
    bodyText: 'The SRA expects solicitors to maintain their competence through continuing learning, including in relation to technology. Where a firm introduces or permits AI tools, it should ensure staff have sufficient training to use those tools safely and within the bounds of professional obligations. Firms with no structured AI training are at higher risk of misuse, confidentiality breaches, and output errors.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'SRA Competence Statement, Part 3; SRA Technology Guidance 2024',
    weight: 1.6,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'Written AI Policy: Market Expectation and Risk Management',
    bodyText: 'A written AI use policy sets out which tools are permitted, what data may be entered, what checks must be applied to outputs, and who is responsible. In the absence of such a policy, staff default to individual judgement — creating inconsistency, confidentiality risk, and traceability gaps. A written policy is increasingly an expectation of PII insurers, corporate clients, and regulators alike.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'SRA Technology Guidance 2024; PII renewal questionnaire benchmarking',
    weight: 1.7,
  },
  {
    category: 'REGULATORY_GUIDANCE',
    title: 'AI Vendor Vetting: Compliance Posture',
    bodyText: 'Not all AI tools carry equivalent compliance risk. Tools designed for legal work and operating under enterprise data processing agreements (e.g. Microsoft 365 Copilot with appropriate configuration, legal-specific AI tools with UK data residency) differ significantly from general-purpose consumer AI products. Firms should conduct due diligence on any AI tool before permitting use with client or matter data, covering: data location, training data use, DPA availability, and penetration testing evidence.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'ICO AI and Data Protection Guidance 2023; SRA Technology Guidance 2024',
    weight: 1.5,
  },

  // ─── USE-CASE LIBRARY (~25 entries) ───────────────────────────────────────

  {
    category: 'USE_CASE_LIBRARY',
    title: 'AI-Assisted Time Capture and Matter Billing',
    bodyText: 'AI-assisted time capture tools analyse emails, documents, and calendar entries to suggest time entries automatically. For firms billing by the hour, this reduces fee-earner time spent on administration and improves billing accuracy. The realistic benefit is a 5–15% increase in captured billable time with reduced write-offs at billing review.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    sourceReference: 'Legal technology adoption survey, 2024',
    weight: 1.4,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Contract Review and Redline Analysis',
    bodyText: 'AI contract review tools can identify non-standard clauses, flag deviations from preferred positions, and highlight missing provisions across large volumes of documents. In M&A due diligence, commercial contracts review, and real estate transactions, these tools reduce the time for initial document triage by 40–70%, freeing lawyers to focus on substantive judgement calls.',
    appliedToPracticeTypes: ['corporate-ma', 'commercial-ip-it', 'conveyancing-property', 'full-service'],
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'Legal AI benchmarking, Thomson Reuters / Bloomberg Law, 2023–2024',
    weight: 1.6,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Legal Research Assistance',
    bodyText: 'AI-augmented legal research tools can surface relevant case law, legislation, and commentary faster than traditional database searches. For litigation, employment, and general advisory work, this can reduce research time by 30–50% while improving coverage. However, outputs must be verified against primary sources — AI hallucination of case citations remains a documented risk.',
    appliedToPracticeTypes: ['litigation-dispute-resolution', 'employment', 'criminal', 'commercial-ip-it', 'full-service'],
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'Legal research AI adoption report, Law Society, 2023',
    weight: 1.5,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Client Intake and Matter Triage',
    bodyText: 'AI-assisted intake tools can categorise new enquiries, check for conflicts, identify the relevant practice area, and route matters to the appropriate fee-earner. For high-volume practices — personal injury, conveyancing, immigration, and employment — this reduces administrative overhead and improves response times. The benefit is most significant for firms handling more than 50 new enquiries per month.',
    appliedToPracticeTypes: ['personal-injury', 'conveyancing-property', 'immigration', 'employment', 'family'],
    appliedToFirmSizes: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    sourceReference: 'Legal operations technology survey, 2024',
    weight: 1.4,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Document Drafting Support',
    bodyText: 'AI writing tools can draft first versions of standard documents — engagement letters, witness statements, standard clauses, court letters — from structured prompts or precedent templates. The benefit is reduction in time for first-draft production; the requirement is always a fee-earner review before any document leaves the firm. Suitable for practices with high document volume where precedent-based drafting is well-established.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'SRA guidance on AI drafting; Law Society Gazette, 2024',
    weight: 1.5,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Conveyancing: AI-Assisted Property Report Preparation',
    bodyText: 'AI tools integrated with conveyancing workflows can extract key information from title registers, searches, and survey reports to prepare structured property reports. This reduces the time for report preparation by 30–50% and reduces the risk of missing material issues. Integration with practice management systems allows automated population of standard fields.',
    appliedToPracticeTypes: ['conveyancing-property'],
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'Conveyancing technology benchmarking, Today\'s Conveyancer, 2024',
    weight: 1.6,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Employment Law: AI-Assisted ET1/ET3 Preparation',
    bodyText: 'AI tools can assist with extracting key facts from chronologies, emails, and HR documents to structure Employment Tribunal claim forms and responses. This is particularly useful for high-volume employment practices and reduces preparation time while maintaining quality. All documents must be reviewed and verified by a qualified solicitor before submission.',
    appliedToPracticeTypes: ['employment'],
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'Employment law technology survey, 2024',
    weight: 1.4,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Wills and Probate: AI-Assisted Estate Administration',
    bodyText: 'AI tools can assist with drafting standard will structures, identifying assets from estate inventories, and preparing letters of administration. For high-volume private client practices, this reduces drafting time and allows fee-earners to focus on client relationships and complex estate planning advice. Systems must be configured to handle sensitive client information in compliance with UK GDPR.',
    appliedToPracticeTypes: ['private-client-wills-probate'],
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'Private client technology survey, STEP, 2024',
    weight: 1.4,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Litigation: AI-Assisted Disclosure Review',
    bodyText: 'AI-assisted document review tools can categorise, prioritise, and identify privileged documents within large disclosure datasets. E-discovery AI has a well-established track record in reducing review costs by 40–80% compared to linear review. Courts have accepted AI-assisted review as reasonable when combined with appropriate quality checks and human oversight.',
    appliedToPracticeTypes: ['litigation-dispute-resolution', 'corporate-ma', 'commercial-ip-it'],
    appliedToFirmSizes: ['MEDIUM', 'LARGE', 'ENTERPRISE'],
    sourceReference: 'EDRM guidelines; Pyrrho Investments v MWB Property [2016] EWHC 256 (Ch)',
    weight: 1.5,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Immigration: AI-Assisted Application Preparation',
    bodyText: 'AI tools can assist with extracting relevant facts from client documentation to populate visa and immigration application forms, cross-checking against current Rules requirements, and identifying supporting evidence gaps. This is particularly useful for high-volume work permit and family visa applications. All applications must be reviewed and authorised by a regulated immigration adviser.',
    appliedToPracticeTypes: ['immigration'],
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'Immigration legal technology survey, ILPA, 2024',
    weight: 1.4,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Corporate/M&A: AI Due Diligence Acceleration',
    bodyText: 'AI due diligence tools can analyse large volumes of corporate documents — articles, shareholder agreements, employment contracts, IP licences, real property — to identify key risks, non-standard positions, and missing items against a standard due diligence checklist. This can reduce the time for initial DD pass by 50–70%, with lawyers focusing on risk assessment rather than document extraction.',
    appliedToPracticeTypes: ['corporate-ma', 'commercial-ip-it'],
    appliedToFirmSizes: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    sourceReference: 'Legal AI benchmarking, M&A tech survey, 2024',
    weight: 1.6,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Family Law: AI-Assisted Financial Disclosure Analysis',
    bodyText: 'In financial remedy proceedings, AI tools can help analyse Form E disclosures, bank statements, and asset schedules to identify patterns, discrepancies, or undisclosed assets. This improves efficiency in complex financial remedy cases. However, extreme care is needed to ensure client-confidential financial data is handled within approved, GDPR-compliant tools only.',
    appliedToPracticeTypes: ['family'],
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'Family law technology survey, Resolution, 2024',
    weight: 1.3,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Transcription and Meeting Summaries',
    bodyText: 'AI transcription and summarisation tools can produce accurate records of client meetings, counsel conferences, and internal reviews. This reduces fee-earner time spent on attendance notes and ensures a more complete record. Firms should ensure any transcription tool being used is cleared for processing client-confidential information and does not retain audio data after processing.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'Legal technology adoption report, 2024',
    weight: 1.3,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Client-Facing AI: FAQ and Status Updates',
    bodyText: 'Client portals with AI-powered FAQ and matter status features can reduce inbound client queries and improve satisfaction for routine updates. Suitable for conveyancing, personal injury, and immigration practices with high volumes of similar queries. Care must be taken to ensure AI responses do not constitute legal advice and are appropriately caveated.',
    appliedToPracticeTypes: ['conveyancing-property', 'personal-injury', 'immigration'],
    appliedToFirmSizes: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    sourceReference: 'Client experience technology survey, 2024',
    weight: 1.2,
  },
  {
    category: 'USE_CASE_LIBRARY',
    title: 'Personal Injury: AI-Assisted Quantum Assessment',
    bodyText: 'AI tools calibrated to Judicial College Guidelines and settlement databases can assist fee-earners in initial quantum assessments for personal injury claims. This improves consistency across a practice and speeds up initial advice on quantum ranges. Final quantum advice must always be given by a qualified solicitor based on the specific facts.',
    appliedToPracticeTypes: ['personal-injury'],
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'PI technology survey, APIL, 2024',
    weight: 1.3,
  },

  // ─── CLIO 2026 (US MARKET CONTEXT) ───────────────────────────────────────
  // The following entry draws on the Clio Legal Trends Report 2026 (a survey of
  // 1,702 US legal professionals). It is included as directional market context
  // only — not as UK-specific data. All UK regulatory obligations are addressed
  // in the REGULATORY_GUIDANCE and RISK_LIBRARY entries above.

  {
    category: 'USE_CASE_LIBRARY',
    title: 'AI Adoption Without Revenue Return: The Efficiency Paradox',
    bodyText: 'US legal market research (Clio Legal Trends Report 2026, a survey of 1,702 US legal professionals — cited here as directional context, not as UK-specific data) found that while 71–75% of solo and small US law firms use AI, only 31–32% have seen increased revenues as a result. The research described this as an efficiency paradox: AI reduces time on tasks but does not automatically convert that saving into revenue — particularly for firms billing by the hour, where time saved on a billable task reduces income unless replaced with new client work. The firms showing the strongest financial returns were not simply those using AI fastest. The US research found their shared characteristics were: reconsidering how work is priced, actively developing their client pipeline, and using tools that function together as an integrated system rather than as a disconnected collection. This directional finding is relevant context for UK law firms: it suggests that AI adoption without a structured approach to how tools are selected, integrated into workflows, and governed may not deliver the expected commercial return — and that the business case for AI readiness extends beyond regulatory compliance.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'Clio Legal Trends Report 2026 (US market research, 1,702 respondents)',
    weight: 1.3,
  },

  // ─── RISK LIBRARY (~20 entries) ───────────────────────────────────────────

  {
    category: 'RISK_LIBRARY',
    title: 'Confidentiality Leakage via Consumer AI Tools',
    bodyText: 'When fee-earners use publicly available AI tools (such as free-tier ChatGPT, Gemini, or similar) and paste client data, case facts, or confidential documents into the interface, that data may be retained and used to train the model. This constitutes a confidentiality breach under SRA Rule 6 and a potential UK GDPR violation. This risk is highest in firms with no written AI policy and no staff training, where individual employees default to convenient consumer tools.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    weight: 2.0,
  },
  {
    category: 'RISK_LIBRARY',
    title: 'Hallucinated Citations and Fabricated Legal Authority',
    bodyText: 'Large language models are known to generate plausible but fictitious case citations, statutory references, and regulatory positions. Several instances have already been reported in the UK and internationally where solicitors have relied on AI-generated case references that did not exist, leading to complaints, sanctions, and wasted court time. The risk is highest where AI research output is not independently verified against primary legal databases.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    weight: 2.0,
  },
  {
    category: 'RISK_LIBRARY',
    title: 'Shadow AI Use by Staff',
    bodyText: 'In most firms, some proportion of fee-earners use AI tools that are not sanctioned by the firm — individual subscriptions to productivity tools, browser extensions, mobile AI apps, or consumer chatbots. This "shadow AI" use is outside the firm\'s data governance, creates confidentiality and GDPR risk, and is invisible to management. Shadow AI is normal and manageable, but only where firms have a clear written policy and regular staff engagement on permitted tools.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.9,
  },
  {
    category: 'RISK_LIBRARY',
    title: 'Unsupervised AI Output in Client-Facing Documents',
    bodyText: 'The risk of AI output reaching clients without adequate review is greatest in high-volume practices where fee-earner time pressure is intense. Documents drafted or substantively edited by AI that are sent to clients without a competent review create professional negligence exposure and, where inaccurate, may lead to client detriment. This risk applies to all correspondence, legal documents, and advice generated with AI assistance.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.8,
  },
  {
    category: 'RISK_LIBRARY',
    title: 'Data Residency Risk: AI Processing Outside UK/EEA',
    bodyText: 'Many widely used AI tools process data on servers based in the United States or other non-UK jurisdictions without adequate transfer mechanisms. Firms that use such tools with client data may be in breach of UK GDPR Chapter V (international transfers) without realising it. The risk is heightened where firms have not reviewed the data processing terms of their AI tools and have no DPAs in place.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.7,
  },
  {
    category: 'RISK_LIBRARY',
    title: 'Bias and Fairness Risk in AI-Assisted Decisions',
    bodyText: 'AI tools trained on historical legal data may embed historical biases — for example, in risk assessments for immigration applications, employment claims, or personal injury quantum. Where an AI tool\'s outputs systematically disadvantage a protected group, this could engage Equality Act 2010 obligations and expose the firm to complaints. Firms should consider diversity, equity, and inclusion implications when deploying AI in client-facing workflows.',
    appliedToPracticeTypes: ['immigration', 'employment', 'personal-injury', 'family', 'criminal'],
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.3,
  },
  {
    category: 'RISK_LIBRARY',
    title: 'Cyber Risk: AI Tools as an Attack Surface',
    bodyText: 'AI tools connected to firm systems — email, document management, practice management software — expand the firm\'s attack surface. Prompt injection attacks, where malicious content in a document causes an AI tool to take unintended actions, are an emerging threat. Firms should ensure that AI integrations are covered by their cyber security policies and that vendor security certifications (e.g. ISO 27001, SOC 2) are verified before deployment.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.5,
  },
  {
    category: 'RISK_LIBRARY',
    title: 'Intellectual Property Risk in AI-Generated Content',
    bodyText: 'The copyright status of AI-generated content is unsettled in the UK. AI outputs that reproduce or closely paraphrase third-party copyrighted material without a licence may expose the firm to IP infringement claims. Conversely, fully AI-generated work product may lack copyright protection, which could affect the firm\'s ability to assert IP rights in its own materials. Firms should take legal advice on their IP position when using AI in document production.',
    appliedToPracticeTypes: ['commercial-ip-it', 'corporate-ma', 'full-service'],
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.2,
  },
  {
    category: 'RISK_LIBRARY',
    title: 'Over-Reliance on AI and Skill Atrophy',
    bodyText: 'Firms that deploy AI heavily without maintaining core legal research and drafting skills risk a gradual deterioration of in-house expertise. Junior solicitors in particular may develop a dependency on AI-generated outputs without building the foundational skills needed to recognise errors. This creates a medium-term quality risk that is not immediately visible in file reviews.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    weight: 1.2,
  },
  {
    category: 'RISK_LIBRARY',
    title: 'Regulatory Risk: Representing AI Use Inaccurately to Clients',
    bodyText: 'Describing legal work to clients, courts, or counterparties in a way that misrepresents the extent of AI involvement — for example, charging for time that was substantially reduced by AI without passing on any saving, or asserting bespoke advice was produced entirely by a solicitor when AI did the first draft — raises risks under SRA Principle 4 (honesty) and may constitute misrepresentation.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.5,
  },
  {
    category: 'RISK_LIBRARY',
    title: 'High Risk: Criminal Practice and AI-Generated Statements',
    bodyText: 'In criminal law, the stakes of AI errors are particularly high. AI tools used to draft witness statements, grounds of appeal, or mitigation documents that contain inaccuracies could directly affect a client\'s liberty. Firms practising criminal law should have the most rigorous review processes for any AI-assisted documents and should be cautious about using AI in any document that will be submitted to court without thorough independent verification.',
    appliedToPracticeTypes: ['criminal'],
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.8,
  },
  {
    category: 'RISK_LIBRARY',
    title: 'DPIA Required: High-Volume AI Processing of Sensitive Data',
    bodyText: 'Firms processing large volumes of sensitive personal data through AI tools — for example, medical records in personal injury, financial records in family proceedings, immigration status data — are likely to trigger the Article 35 UK GDPR DPIA requirement for high-risk processing. Operating without a DPIA in these circumstances exposes the firm to ICO enforcement action.',
    appliedToPracticeTypes: ['personal-injury', 'family', 'immigration', 'criminal'],
    appliedToFirmSizes: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    sourceReference: 'UK GDPR Article 35; ICO DPIA Guidance 2023',
    weight: 1.6,
  },

  // ─── CLIO 2026 (US MARKET CONTEXT) ───────────────────────────────────────
  // The following two entries draw on the Clio Legal Trends Report 2026 (a
  // survey of 1,702 US legal professionals). Included as directional market
  // benchmarking only — not as UK-specific regulatory data.

  {
    category: 'RISK_LIBRARY',
    title: 'AI Policy Gap: How Widespread Is the Absence of Governance?',
    bodyText: 'US legal market research (Clio Legal Trends Report 2026, a survey of 1,702 US legal professionals — cited here as directional context, not as UK-specific data) found that 57% of solo US law firms and 55% of small US law firms operate without any formal AI usage policy. The finding is consistent with what UK practitioners and regulators observe in this market. For UK law firms, the absence of a written AI policy is not simply a common shortfall to be normalised — it carries specific consequences. SRA Technology Guidance 2024 and PII insurers increasingly expect documented AI governance. Without a policy, fee-earners default to individual judgement on which tools to use and what data to enter, creating inconsistency that is difficult to supervise or evidence to a client, insurer, or regulator. The US research provides directional benchmarking: operating without an AI policy is statistically common in comparable legal markets, but that prevalence does not reduce the UK regulatory and professional obligations to have one in place.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'Clio Legal Trends Report 2026 (US market research, 1,702 respondents); SRA Technology Guidance 2024',
    weight: 1.4,
  },
  {
    category: 'RISK_LIBRARY',
    title: 'Generic Tool Fragmentation: Operational Risk Beyond Compliance',
    bodyText: 'US legal market research (Clio Legal Trends Report 2026, a survey of 1,702 US legal professionals — cited here as directional context, not as UK-specific data) found that 47–48% of solo and small US law firms rely primarily on generic consumer AI tools, and that many operate a fragmented collection of disconnected tools — resulting in redundant data entry, multiple logins, and time lost switching between systems. Beyond the confidentiality and UK GDPR risks of consumer tools (which are addressed separately in this knowledge base), this operational fragmentation carries an additional risk: it makes uniform governance controls harder to apply and harder to evidence. When different fee-earners use different tools, chosen individually, a firm cannot demonstrate consistent data handling, consistent output verification, or consistent compliance with its own AI policy. For UK law firms, a patchwork of individually-adopted tools — even where each is used carefully — creates governance gaps that are difficult to monitor and difficult to evidence to a regulator, insurer, or client if challenged.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'Clio Legal Trends Report 2026 (US market research, 1,702 respondents)',
    weight: 1.3,
  },

  // ─── CONDITIONAL EU LAYER (~5 entries) ────────────────────────────────────

  {
    category: 'CONDITIONAL_EU_LAYER',
    title: 'EU AI Act: Scope and Applicability for UK Law Firms',
    bodyText: 'The EU AI Act entered into force in August 2024, with obligations phasing in through 2025–2026. UK-based law firms advising EU-based clients, processing data from EU individuals, or using AI tools provided by EU-regulated suppliers may fall within scope. The Act imposes tiered obligations based on AI risk classification, with prohibited systems, high-risk requirements, and transparency obligations for general-purpose AI. This is an additional compliance layer that will be analysed in detail in the full NexterLaw AI Readiness & Compliance Audit.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'EU AI Act (Regulation 2024/1689), OJ L 2024/1689',
    weight: 1.5,
    isEuLayerEntry: true,
  },
  {
    category: 'CONDITIONAL_EU_LAYER',
    title: 'EU AI Act: High-Risk AI Systems in Legal Contexts',
    bodyText: 'The EU AI Act classifies AI used in the administration of justice and legal services as potentially high-risk (Annex III). AI tools used to assess case outcomes, evaluate evidence, or significantly influence legal decisions may carry high-risk obligations including conformity assessments, technical documentation, and human oversight requirements. Firms advising EU clients or using EU-regulated AI tools should assess each tool against the high-risk classification criteria.',
    appliedToPracticeTypes: ['litigation-dispute-resolution', 'immigration', 'employment', 'family', 'criminal'],
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'EU AI Act Annex III, Article 6',
    weight: 1.4,
    isEuLayerEntry: true,
  },
  {
    category: 'CONDITIONAL_EU_LAYER',
    title: 'EU AI Act: Transparency Obligations for AI-Generated Content',
    bodyText: 'The EU AI Act requires disclosure where AI is used to generate content that could mislead users about its artificial origin. For law firms, this may apply to AI-drafted correspondence, reports, or advisory documents sent to EU-based clients or counterparties. Transparency obligations under the Act are separate from — and in addition to — SRA disclosure expectations.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'EU AI Act Articles 50, 52',
    weight: 1.3,
    isEuLayerEntry: true,
  },
  {
    category: 'CONDITIONAL_EU_LAYER',
    title: 'EU AI Act and UK GDPR Interplay',
    bodyText: 'Where a UK law firm is subject to both UK GDPR and the EU AI Act (through GDPR Article 3 extraterritorial scope applied to EU data subjects), both regulatory frameworks must be satisfied simultaneously. DPIAs conducted for AI under UK GDPR should be cross-referenced against EU AI Act conformity assessment requirements. The full NexterLaw Audit will map these overlapping obligations for your specific practice profile.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'EU AI Act Article 2; GDPR Article 3',
    weight: 1.3,
    isEuLayerEntry: true,
  },
  {
    category: 'CONDITIONAL_EU_LAYER',
    title: 'EU AI Act: General Purpose AI Model Obligations',
    bodyText: 'General-purpose AI tools (such as large language models used for drafting, research, or analysis) used by firms in EU-facing work may carry additional obligations under EU AI Act Title X, including transparency requirements about model capabilities and training data. From mid-2025, providers of general-purpose AI with systemic risk designation must comply with additional monitoring, incident reporting, and adversarial testing requirements.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    sourceReference: 'EU AI Act Articles 51–55 (Title X)',
    weight: 1.2,
    isEuLayerEntry: true,
  },

  // ─── TOOL CATEGORIES (~15 entries) ────────────────────────────────────────

  {
    category: 'TOOL_CATEGORIES',
    title: 'Legal Research AI Platforms',
    bodyText: 'AI-augmented legal research tools integrated with primary law databases. Example products in this category include Westlaw Edge, LexisNexis+AI, and vLex Vincent. These tools are purpose-built for legal use, retrieve from verified primary sources, and include citation verification — significantly reducing hallucination risk compared to general-purpose AI. Most major providers offer UK-specific data and GDPR-compliant processing.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.5,
  },
  {
    category: 'TOOL_CATEGORIES',
    title: 'Document Review and E-Discovery AI',
    bodyText: 'AI-assisted document review platforms for disclosure, due diligence, and contract analysis. Example products in this category include Relativity, Luminance, and Kira Systems. Enterprise-grade tools in this category offer UK data residency, SOC 2 and ISO 27001 certification, and DPAs suitable for processing client data. Pricing is typically usage-based, making them accessible to smaller firms on a per-matter basis.',
    appliedToPracticeTypes: ['litigation-dispute-resolution', 'corporate-ma', 'commercial-ip-it'],
    appliedToFirmSizes: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    weight: 1.5,
  },
  {
    category: 'TOOL_CATEGORIES',
    title: 'Conveyancing and Property AI Tools',
    bodyText: 'AI tools purpose-built for conveyancing workflows, including automated title report drafting, search result analysis, and mortgage instruction processing. Example products in this category include Smoove (formerly Easyconvey), InfoTrack, and Orbital Witness for property title analysis. These tools integrate with common conveyancing platforms and are designed for UK residential and commercial property transactions.',
    appliedToPracticeTypes: ['conveyancing-property'],
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.5,
  },
  {
    category: 'TOOL_CATEGORIES',
    title: 'AI-Assisted Time Recording and Billing',
    bodyText: 'Tools that use AI to suggest time entries from email, document, and calendar activity. Example products in this category include tools integrating with Clio, Elite, and LEAP practice management systems. These tools operate within the firm\'s existing IT environment and typically process data within UK/EEA infrastructure for firms with appropriate configurations. They reduce administrative burden without requiring client data to be shared externally.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.3,
  },
  {
    category: 'TOOL_CATEGORIES',
    title: 'Microsoft 365 Copilot for Legal',
    bodyText: 'Microsoft 365 Copilot integrates AI across Word, Outlook, Teams, and SharePoint. For firms already using Microsoft 365, Copilot can be enabled through an enterprise licence. When properly configured, Microsoft processes Copilot data within the firm\'s Microsoft 365 tenant — not for model training — and provides UK/EEA data residency options. Firms should review the Microsoft Copilot data protection addendum and ensure it is in place before use with client data.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    sourceReference: 'Microsoft Copilot Data Protection Addendum; Microsoft Trust Center',
    weight: 1.4,
  },
  {
    category: 'TOOL_CATEGORIES',
    title: 'General Purpose AI: Enterprise Versions',
    bodyText: 'Enterprise versions of general-purpose AI tools (such as Claude for Enterprise, ChatGPT Enterprise, and Gemini for Workspace) offer data processing agreements, zero-retention policies, and in some cases UK/EEA data residency. These differ materially from their consumer equivalents and may be appropriate for use with some client data once firm-specific DPAs are in place. Firms should obtain and review the DPA before enabling use with client information.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ['MEDIUM', 'LARGE', 'ENTERPRISE'],
    sourceReference: 'Provider-specific DPAs and trust centres',
    weight: 1.3,
  },
  {
    category: 'TOOL_CATEGORIES',
    title: 'AI Transcription and Note-Taking',
    bodyText: 'AI transcription tools for meetings, calls, and dictation. Example products in this category include Otter.ai for Business, Microsoft Teams transcription, and Nuance Dragon Legal. For use with client calls or meetings, the tool must not retain audio or transcripts on external servers without a DPA, and clients should be informed (and consent where required). Enterprise and legal editions typically offer appropriate compliance controls.',
    appliedToPracticeTypes: ALL_PRACTICES,
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.2,
  },
  {
    category: 'TOOL_CATEGORIES',
    title: 'Legal-Specific AI Drafting Assistants',
    bodyText: 'AI drafting tools built specifically for legal work, with legal-trained models and precedent libraries. Example products in this category include Harvey AI (legal-specific LLM), Spellbook (contract drafting), and Definely (document analysis). These tools are designed for legal workflows, process data under enterprise DPAs, and in some cases offer UK data residency. They represent a more compliance-appropriate choice than general-purpose AI for firms handling sensitive client data.',
    appliedToPracticeTypes: ['corporate-ma', 'commercial-ip-it', 'litigation-dispute-resolution', 'full-service'],
    appliedToFirmSizes: ['MEDIUM', 'LARGE', 'ENTERPRISE'],
    weight: 1.4,
  },
  {
    category: 'TOOL_CATEGORIES',
    title: 'Immigration AI Case Management',
    bodyText: 'AI-assisted case management tools purpose-built for immigration practice, including automated visa route identification, checklist generation, and Home Office form population. Example products in this category include Migrate (immigration SaaS) and integrated AI modules within specialist immigration case management platforms. These tools are designed with UK immigration law in mind and process data within compliant infrastructure.',
    appliedToPracticeTypes: ['immigration'],
    appliedToFirmSizes: ALL_SIZES,
    weight: 1.3,
  },
  {
    category: 'TOOL_CATEGORIES',
    title: 'AI Client Portal and Self-Service',
    bodyText: 'Client-facing portals with AI-powered FAQ, matter status, and document upload capabilities. Example products in this category include Clio Grow, Actionstep, and bespoke portal solutions. These tools must be configured to ensure AI responses do not constitute legal advice, that data is processed within compliant infrastructure, and that clients are clearly informed about the use of AI in the portal.',
    appliedToPracticeTypes: ['conveyancing-property', 'personal-injury', 'immigration', 'employment'],
    appliedToFirmSizes: ['SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE'],
    weight: 1.2,
  },
];
